import { NextResponse } from 'next/server'
import { readFile } from 'fs/promises'
import { join } from 'path'

const FACE_MAPPING_PATH = join(process.cwd(), 'data', 'simli-face-ids.json')

/**
 * GET /api/timeless-minds/simli-faces
 *
 * Returns the mapping of thinker IDs to Simli face IDs.
 * These are generated by the face upload script.
 */
export async function GET() {
  try {
    const data = await readFile(FACE_MAPPING_PATH, 'utf-8')
    const mapping = JSON.parse(data)
    return NextResponse.json(mapping)
  } catch {
    // File doesn't exist yet, return empty mapping
    return NextResponse.json({})
  }
}
